apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuelconsumption
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuelconsumption
  template:
    metadata:
      labels:
        app: fuelconsumption
    spec:
      containers:
        - name: fuelconsumption
          image: fuelconsumption:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DISPLAY
              value: ":0"
---
apiVersion: v1
kind: Service
metadata:
  name: fuelconsumption-service
spec:
  selector:
    app: fuelconsumption
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP