sonar.projectKey=fuelEliasRinne
sonar.projectName=fuelEliasRinne
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.token=squ_d62721bc24527d094af4abbaf40e9572509e0cec